version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=example
      - DB_NAME=school_fees_system
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: school_fees_system
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
